# Generated by Django 2.2 on 2020-03-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_likecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
